.circleci/config.yml
Make the package public and add more packages from different folders
=> [ci] add protocols and helpers folders, update to public

package.json, protocols/swap/contracts/Migrations.sol, protocols/swap/package.json
Re-added packages
Updated Migration.sol to be inline with solidity recs
=> clean up packages and Migrations.sol

protocols/indexer/contracts/Indexer.sol, protocols/market/contracts/Market.sol
`slither Indexer.sol`
handle 
`public-function-that-could-be-declared-as-external`
=> Slither Market and Indexer

helpers/wrapper/contracts/Wrapper.sol
> initial design may have anticipated a need but can't imagine one now
=> Wrapper swapSimple() to external

protocols/peer/README.md, protocols/peer/contracts/Peer.sol, protocols/peer/contracts/interfaces/IPeer.sol
Update the input params and return value names for getTakerSideQuote, getMakerSideQuote, and getMaxQuote
=> update quote naming convention

README.md, protocols/swap/reports/SECURITY.md, protocols/swap/reports/slither.txt
Updated contract addresses for mainnet swap
Remove remnants of swapSimple from report
=> update docs after mainnet deploy

protocols/peer/README.md, protocols/peer/contracts/PeerFactory.sol, protocols/peer/contracts/interfaces/IPeerFactory.sol, protocols/peer/test/Peer.js
Add PeerFactory to readme.md
Have PeerFactory.createPeer return the peercontractAddress
Some small naming changes
Added some Peer integration tests
=> Peer factory return value

examples/consumer/contracts/Consumer.sol, examples/consumer/test/Consumer-unit.js, helpers/wrapper/contracts/Wrapper.sol, helpers/wrapper/test/Wrapper-unit.js, helpers/wrapper/test/Wrapper.js, packages/order-utils/src/constants.js, packages/order-utils/src/orders.js, packages/order-utils/src/signatures.js, packages/order-utils/test/signatures.js, protocols/peer/README.md, protocols/peer/contracts/Peer.sol, protocols/peer/contracts/interfaces/IPeer.sol, protocols/peer/test/Peer-unit.js, protocols/peer/test/Peer.js, protocols/swap/MIGRATION.md, protocols/swap/README.md, protocols/swap/contracts/Swap.sol, protocols/swap/contracts/interfaces/ISwap.sol, protocols/swap/test/Swap-unit.js, protocols/swap/test/Swap.js, protocols/types/contracts/Types.sol, protocols/types/test/Types-unit.js
Rather than having order and signature be side-by-side, including signature as a property of order.
=> Adding signature to order

protocols/indexer/contracts/Indexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/market/contracts/Market.sol, protocols/market/migrations/2_deploy_contracts.js, protocols/market/test/Market-unit.js, protocols/market/test/Market.js
Removing makerToken and takerToken from Market and other changes to make Market less application-specific.
=> Making Market more generic

examples/consumer/package.json, helpers/wrapper/package.json, packages/order-utils/package.json, protocols/indexer/package.json, protocols/market/package.json, protocols/peer/package.json, protocols/swap/package.json, protocols/types/package.json, yarn.lock
swap from 2.0.0 to 2.1.0
indexer from 0.1.0 to 0.2.0
market from 0.1.0 to 0.2.0
peer from 0.2.0 to 0.3.0
types from 0.1.0 to 0.2.0
wrapper from 0.1.0 to 0.2.0
order-utils from 0.2.0 to 0.3.0
=> Updating package versions for publishing

README.md, protocols/swap/README.md, protocols/swap/package.json
Also moves contract deployments into their respective package README
=> Moving swap docs out and updating primary README

protocols/index/contracts/Imports.sol, protocols/index/contracts/Index.sol
Two changes: 
With the remove of tokens from index (market), there are no imports required for testing 
Noticed capital Locator variable and thus lowercased it
100% coverage
=> Resolve shadow in index

protocols/peer-factory/README.md
update contract in Rinkeby in etherscan.
=> update rinkeby address

helpers/wrapper/reports/SECURITY.md
* Updates to language and formatting
* Adds invariants 6, 10, and 11
=> Language and invariant updates for Wrapper security report

helpers/wrapper/README.md, helpers/wrapper/package.json, helpers/wrapper/reports/SECURITY.md
Update wrapper address and port over addresses to README.md
Not affected.
=> update wrapper readme

helpers/wrapper/README.md
Updated messaging on the wrapper readme
Purely README.md change.
=> wrapper readme update

helpers/peer-frontend/contracts/PeerFrontend.sol, helpers/peer-frontend/test/PeerFrontend-unit.js, helpers/peer-frontend/test/PeerFrontend.js, helpers/wrapper/contracts/Wrapper.sol, helpers/wrapper/test/Wrapper.js, protocols/peer-factory/contracts/PeerFactory.sol, protocols/peer-factory/contracts/interfaces/IPeerFactory.sol, protocols/peer-factory/test/Peer-factory-unit.js, protocols/peer/contracts/Peer.sol, protocols/peer/contracts/interfaces/IPeer.sol, protocols/peer/migrations/2_deploy_contracts.js, protocols/peer/test/Peer-unit.js, protocols/peer/test/Peer.js, yarn.lock
- Fix for github issue https://github.com/airswap/airswap-protocols/issues/148
- Addition of more tests into Peer.js to increase the coverage of the integration tests to 100%
```
Imports.sol          |      100 |      100 |      100 |      100 |                |
Peer.sol             |      100 |      100 |      100 |      100 |                |
contracts/interfaces/ |      100 |      100 |      100 |      100 |                |
IPeer.sol            | …
```
=> Peer trade wallet

PULL_REQUEST_TEMPLATE.md
Adding a PR template for this repository to ensure adding test and test coverage within the PR.
added a PULL_REQUEST_TEMPLATE.md to the root level for repository
Not affected
Not affected
=> adding PR template w test coverage

.solhintignore, package.json, protocols/delegate-factory/contracts/interfaces/IDelegateFactory.sol
Adding to `.solhintignore` and fixing yarn script to run it. `yarn hint`
=> Updating solhint command and lint fix for IDelegateFactory

helpers/delegate-frontend/package.json, helpers/wrapper/package.json, packages/order-utils/package.json, packages/order-utils/src/orders.js, packages/order-utils/test/signatures.js, protocols/delegate/package.json, protocols/index/package.json, protocols/swap/package.json
Small syntax fix and bumping version so that recent changes are published to NPM.
=> Syntax quick fixes and version bump for publishing

protocols/swap/contracts/Swap.sol, protocols/swap/contracts/interfaces/ISwap.sol, protocols/swap/test/Swap-unit.js, protocols/swap/test/Swap.js
Implements #184 to reduce nonce states in Swap.sol to just AVAILABLE or UNAVAILABLE
```
// Possible nonce statuses
byte constant private AVAILABLE = 0x00;
byte constant private UNAVAILABLE = 0x01;
```
=> Changes to address #184 re: nonce states in Swap.sol

protocols/indexer/contracts/Indexer.sol, protocols/indexer/contracts/interfaces/IIndexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/indexer/test/Indexer.js
`addToBlacklist` and `removeFromBlacklist` now take an address not a list of addresses.
Very small change to each of addToBlacklist and removeFromBlacklist
All passing
=> Blacklist parameters

protocols/index/contracts/Index.sol, protocols/index/test/Index-unit.js, protocols/indexer/contracts/Indexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/indexer/test/Indexer.js
See issue https://github.com/airswap/airswap-protocols/issues/187 for a description of the changes and the motivation.
=> Linked list new structure

protocols/indexer/contracts/Indexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/indexer/test/Indexer.js
https://github.com/airswap/airswap-protocols/issues/181
=> Pausable indexer

helpers/delegate-frontend/contracts/DelegateFrontend.sol, helpers/delegate-frontend/migrations/2_deploy_contracts.js, helpers/delegate-frontend/test/DelegateFrontend-unit.js, helpers/delegate-frontend/test/DelegateFrontend.js, protocols/delegate-factory/contracts/DelegateFactory.sol, protocols/delegate-factory/contracts/Imports.sol, protocols/delegate-factory/contracts/interfaces/IDelegateFactory.sol, protocols/delegate-factory/migrations/2_deploy_contracts.js, protocols/delegate-factory/test/Delegate-Factory-unit.js, protocols/delegate/contracts/Delegate.sol, protocols/delegate/migrations/2_deploy_contracts.js, protocols/delegate/test/Delegate-unit.js, protocols/delegate/test/Delegate.js, protocols/indexer/contracts/Indexer.sol, protocols/indexer/migrations/2_deploy_contracts.js, protocols/indexer/test/Indexer-unit.js, protocols/indexer/test/Indexer.js
=> delegate to have indexer in constructor

.solhint.json, helpers/delegate-frontend/contracts/DelegateFrontend.sol, protocols/delegate-factory/contracts/DelegateFactory.sol, protocols/delegate/contracts/Delegate.sol, protocols/delegate/contracts/interfaces/IDelegate.sol, protocols/index/contracts/Index.sol, protocols/indexer/contracts/Indexer.sol, protocols/indexer/contracts/interfaces/IIndexer.sol, protocols/types/contracts/Types.sol
=> Solhint update

.circleci/config.yml
=> adding solhint to circleci

helpers/delegate-frontend/contracts/DelegateFrontend.sol, helpers/wrapper/contracts/Wrapper.sol, protocols/delegate-factory/contracts/DelegateFactory.sol, protocols/delegate/contracts/Delegate.sol, protocols/index/contracts/Index.sol, protocols/indexer/contracts/Indexer.sol, protocols/swap/contracts/Swap.sol, protocols/swap/contracts/interfaces/ISwap.sol, protocols/swap/test/Swap-unit.js, protocols/types/contracts/Types.sol
- Comments are full sentences, starting with a capital, ending with a .
- Natspec format uniform across contracts
=> making natspec format consistent

protocols/swap/contracts/Swap.sol, protocols/swap/contracts/interfaces/ISwap.sol
=> style guide

protocols/delegate/test/Delegate-unit.js
https://www.notion.so/fluidity/Protocols-Review-and-Cleanup-dbe74358035b4bf2ac01847a73044d2d
```
68 passing (8s)
Delegate.sol         |      100 |      100 |      100 |      100 |                |
Imports.sol          |      100 |      100 |      100 |      100 |                |
contracts/interfaces/ |      100 |      100 |      100 |      100 |                |
IDelegate.sol        |      100 |      100 |      100 |      100 |                | …
```
=> Coverage Delegate

helpers/wrapper/contracts/Wrapper.sol
Wrapper updated to meet style guide
=> wrapper style guide

protocols/index/contracts/Index.sol
Index updated to meet style guide
=> index style guide

helpers/wrapper/contracts/Wrapper.sol, protocols/types/contracts/Types.sol
Types updated to meet style guide
=> Types style guide

protocols/delegate-factory/contracts/DelegateFactory.sol, protocols/delegate-factory/contracts/interfaces/IDelegateFactory.sol
=> Delegate factory style guide

protocols/delegate/contracts/Delegate.sol, protocols/delegate/contracts/interfaces/IDelegate.sol
Delegate updated to meet style guide
=> delegate style guide

protocols/indexer/contracts/Indexer.sol, protocols/indexer/contracts/interfaces/IIndexer.sol, protocols/indexer/contracts/interfaces/ILocatorWhitelist.sol
Indexer updated to meet style guide
=> Indexer style guide

source/index/contracts/Index.sol, source/index/test/Index-unit.js
Fix for https://github.com/airswap/airswap-protocols/issues/220
- Made the entries mapping public
- Added tests for retrieving entries
=> entries public and tests

package.json, source/indexer/test/Indexer.js, yarn.lock
- Added husky to the repo - a package that handles generation of git hooks for you
- Added 2 default commands, but these are up for discussion. Would love people's opinions on what they would like.
Unchanged
=> Pre commit hooks

source/wrapper/reports/SECURITY.md
Small updates for the wrapper update
Updated the wrapper.security.md to better reflect current repo state.
No changes
No changes
=> added small updates to wrapper security report

source/swap/reports/SECURITY.md, source/swap/reports/slither.txt, source/types/contracts/Types.sol
Update SWAP security for naming changes and slither update
Style update in Types.sol
5 passing (1s)
lerna success run Ran npm script 'test' in 8 packages in 194.6s:
Done in 209.61s.
No changes to codebase besides rename.
=> update report and types style change

source/swap/contracts/Swap.sol, source/swap/test/Swap-unit.js, source/swap/test/Swap.js
Small updates to the `transferToken` function.
=> Content update for Swap transferToken

source/wrapper/contracts/Wrapper.sol, source/wrapper/test/Wrapper-unit.js
https://github.com/airswap/airswap-protocols/issues/239
- added modifiers `paused()` and `notPaused()`
- added `setPausedStatus()`
- added `killContract()`
- added modifiers to swap() and `killContract()` 
```
38 passing (11s)
Imports.sol |      100 |      100 |      100 |      100 |                |
Wrapper.sol |      100 |      100 |      100 |      100 |                |
All files     | …
```
=> Add Pausable Modifiers to Wrapper

source/index/contracts/Index.sol
Added a line to comments portion of Index contract explaining the behavior.
N/A
N/A
=> #238 update the index natspec

source/delegate/test/Delegate.js, source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol, source/swap/test/Swap-unit.js, source/swap/test/Swap.js, source/wrapper/test/Wrapper.js
Code change is small, remove the expiry time in authorizeSender and authorizerSigner and instead use a bool. 
The rest of the changes are all tests
```
lerna success run Ran npm script 'test' in 8 packages in 212.4s:
Done in 220.56s.
contracts/   |      100 |      100 | …
```
=> address issue #194 ie remove expiry in swap.sol

source/delegate/contracts/Delegate.sol, source/delegate/contracts/interfaces/IDelegate.sol, source/types/contracts/Types.sol
- Added indexed events to Delegate (#236)
- Moved struct Rule from Types to Delegate (#230)
- Add ruleOwner to setRule and unsetRule in IDelegate (#210)
```
5 passing (1s)
lerna success run Ran npm script 'test' in 8 packages in 192.5s:
Done in 200.41s.
Still 100%```
=> added indexed events to Delegate + adding ruleOwner

source/index/contracts/Index.sol, source/index/test/Index-unit.js, source/indexer/contracts/Indexer.sol, source/indexer/contracts/interfaces/IIndexer.sol, source/indexer/reports/SECURITY.md, source/indexer/test/Indexer-unit.js, source/indexer/test/Indexer.js
https://github.com/airswap/airswap-protocols/issues/237 and https://github.com/airswap/airswap-protocols/issues/235
See issues linked above for details.
=> Indexer issues

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/indexer/test/Indexer.js, source/swap/package.json, source/tokens/package.json, source/types/package.json, yarn.lock
Implements #251. Moving some dependencies to devDependencies
Changes to package.json in affected packages.
=> Moving some dependencies to devDependencies

source/delegate/contracts/Delegate.sol, source/delegate/contracts/interfaces/IDelegate.sol, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js
Added an event to Delegate.provideOrder, outputted on successful swap.
All passing
All passing
=> Delegate event

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json
=> Update patch versions

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/wrapper/package.json, utils/test-utils/package.json
test-utils 0.1.0 -> 0.1.1
```
lerna success run Ran npm script 'test' in 8 packages in 126.9s:
✨  Done in 130.48s.
```
=> Update Test Utils 0.1.1

.circleci/config.yml
=> Fix NPM publish utils

package.json, source/delegate-factory/test/Delegate-Factory-unit.js, source/delegate/test/Delegate-unit.js, source/index/test/Index-unit.js, source/indexer/test/Indexer-unit.js, source/indexer/test/Indexer.js, source/swap/test/Swap-unit.js, source/swap/test/Swap.js, source/types/test/Types-unit.js, source/wrapper/test/Wrapper-unit.js, source/wrapper/test/Wrapper.js, utils/test-utils/src/time.js, yarn.lock
I noticed we weren't using the most up to date package and naming.
=> Update Ganache Time Traveler

source/delegate-factory/package.json, source/index/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json, yarn.lock
Updating version of airswap tokens used to the correct one.
=> fixing tokens version

source/indexer/reports/SECURITY.md
Updated indexer report to reflect naming changes and additions to the contract. 
N/A
N/A
=> updated the indexer-report

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/swap/package.json, source/wrapper/package.json, utils/order-utils/package.json
=> Patch version bump to publish order-utils

source/delegate/contracts/Delegate.sol, source/delegate/contracts/Migrations.sol, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js
In reference to https://github.com/airswap/airswap-protocols/issues/274
Adding checks in the beginning and end of setRuleAndIntent to handle incrementing or decrementing staked tokens if they already exists
36 passing (25s)
```
79 passing (1m)
Delegate.sol         |      100 |      100 |      100 |      100 |                |
Imports.sol          |      100 |      100 |      100 |      100 |                |
contracts/interfaces/ | …
```
=> added commit for #273 and fixing unit tests

.eslintrc.json, source/delegate-factory/test/Delegate-Factory-unit.js, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js, source/index/test/Index-unit.js, source/indexer/test/Indexer-unit.js, source/indexer/test/Indexer.js, source/swap/test/Swap-unit.js, source/swap/test/Swap.js, source/types/test/Types-unit.js, source/wrapper/test/Wrapper-unit.js, source/wrapper/test/Wrapper.js, utils/order-utils/src/orders.js, utils/order-utils/test/orders.js, utils/test-utils/src/padding.js, utils/test-utils/src/time.js
- Added rule `"prefer-const": "error"` to the eslint configuration
- Ran `yarn lint --fix`
=> eslint fix

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json
Updated ganache command in the sub repos
=> Update ganache command

README.md, source/tokens/contracts/AdaptedERC721.sol, source/tokens/contracts/IERC721Receiver.sol, source/tokens/contracts/OrderTest721.sol, utils/order-utils/package.json, utils/order-utils/src/orders.js, utils/order-utils/test/orders.js, yarn.lock
Added checks to `checkOrder` for swaps that include ERC721s
=> Order check nft

source/indexer/test/Indexer-unit.js
Added two more tests to cover a missing test branch case. In case a transfer of staking tokens fails when either increasing or decreasing the score, the staked amount should stay the same.
[X] Typo/small tweaks
```
92 passing (2m)
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
contracts/             |      100 |      100 |      100 |      100 |                |
Imports.sol           |      100 |      100 |      100 |      100 |                |
Indexer.sol           |      100 |      100 …
```
=> increased indexer test coverage to 100%

source/indexer/contracts/Indexer.sol, source/indexer/contracts/interfaces/IIndexer.sol, source/indexer/test/Indexer-unit.js
https://github.com/airswap/airswap-protocols/issues/290
```
emit CreateIndex(signerToken, senderToken);
```
has become
```
emit CreateIndex(signerToken, senderToken, address(indexes[signerToken][senderToken]));
```
```
92 passing (17s)
```
=> CreateIndex event emits the created index

source/swap/contracts/Swap.sol
https://github.com/airswap/airswap-protocols/issues/294
Update the `Swap.cancel()` to properly indicate issues with gas usage and how to remedy.
Update @dev with description of gas usage.
N/A
=> QSP-7 Gas Usage / for Loop Concerns - Swap.cancel()

source/delegate-factory/README.md, source/delegate/README.md, source/index/README.md, source/indexer/README.md, source/swap/README.md, source/types/README.md
Quick description: Adding a note for testing Delegate contracts
Non-functional change
=> Adding a note for testing Delegate contracts

source/wrapper/README.md
Adding a note about testing requirements.
=> Adding note to Wrapper

source/index/package.json, source/swap/package.json, source/tokens/package.json, source/types/package.json, source/wrapper/package.json, utils/order-utils/package.json
=> Bumping tokens for publish and updating description

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json, utils/order-utils/package.json
Bumping order-utils to update its tokens dependency version
=> Bumping order-utils to update its tokens dependency version

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/contracts/interfaces/ISwap.sol, source/swap/package.json, source/types/package.json, source/wrapper/package.json, utils/order-utils/package.json
ISwap had an incorrect return type for 2 functions. This is a remnant from when we have expiries.
=> Updating return type of ISwap functions

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json, utils/order-utils/package.json, utils/order-utils/src/signatures.js
`ecsign` was returning Buffer instead of hex.
=> Converting buffer to hex for ecsign signatures

scripts/identify_dependencies.py
=> works with python 3.5!

source/delegate/package.json, source/index/README.md, source/index/package.json, source/indexer/README.md, source/indexer/package.json, source/wrapper/README.md, source/wrapper/package.json
Removing warnings from Indexer, Index, Wrapper
=> Removing warnings from Indexer, Index, Wrapper

package.json, source/delegate-factory/migrations/1_initial_migration.js, source/delegate-factory/truffle-config.js, source/delegate/migrations/1_initial_migration.js, source/delegate/truffle-config.js, source/index/migrations/1_initial_migration.js, source/index/truffle-config.js, source/indexer/migrations/1_initial_migration.js, source/indexer/truffle-config.js, source/swap/migrations/1_initial_migration.js, source/swap/truffle-config.js, source/tokens/truffle-config.js, source/types/migrations/1_initial_migration.js, source/types/truffle-config.js, source/wrapper/migrations/1_initial_migration.js, source/wrapper/truffle-config.js
=> Setup Migrations to target Mainnet

package.json, source/delegate-factory/README.md, source/delegate-factory/package.json, source/delegate/package.json, source/indexer/README.md, source/indexer/package.json, source/swap/README.md, source/swap/package.json, source/types/README.md, source/types/package.json, source/wrapper/README.md, source/wrapper/package.json, utils/order-utils/package.json
Referencing deploys.json from README, removing warning from DelegateFactory
=> Referencing deploys.json from README

source/delegate/README.md
Quick documentation add regarding running solidity-coverage
N/A
N/A
=> Coverage readme update

.circleci/config.yml
=> remove persisting to workspace for all tests

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json, utils/deployer/package.json, utils/order-utils/README.md, utils/order-utils/package.json, utils/test-utils/README.md, utils/test-utils/package.json
README.md for order-utils and test-utils
=> Readmes for Test and Order utils

.circleci/config.yml, utils/pre-swap-checker/README.md, utils/pre-swap-checker/contracts/Imports.sol, utils/pre-swap-checker/contracts/Migrations.sol, utils/pre-swap-checker/contracts/PreSwapChecker.sol, utils/pre-swap-checker/migrations/1_initial_migration.js, utils/pre-swap-checker/package.json, utils/pre-swap-checker/test/PreSwapChecker.js, utils/pre-swap-checker/truffle-config.js
Takes in a sample order and outputs a bytes32[] of length 10. If there are errors found they will be embedded within the array.
```
18 passing (10s)
---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
contracts/          |      100 |      100 |      100 |      100 |                |
Imports.sol        |      100 |      100 |      100 |      100 |                |
PreSwapChecker.sol |      100 |      100 |      100 |      100 |                |
---------------------|----------|----------|----------|----------|----------------|
All files            |      100 |      100 | …
```
=> add in the pre-swap-checker

.circleci/config.yml, source/delegate/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json, utils/deployer/package.json, utils/order-utils/package.json, utils/pre-swap-checker/package.json
=> Fixing circleci hang

package.json, source/delegate/contracts/Delegate.sol, source/delegate/contracts/DelegateFactory.sol, source/delegate/package.json, source/delegate/test/Delegate-Factory-unit.js, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js, source/indexer/contracts/Indexer.sol, source/indexer/contracts/interfaces/IIndexer.sol, source/indexer/package.json, source/indexer/test/Indexer-unit.js, source/indexer/test/Indexer.js, source/swap/package.json, source/types/package.json, source/wrapper/package.json, source/wrapper/test/Wrapper-unit.js, source/wrapper/test/Wrapper.js
https://github.com/airswap/airswap-protocols/issues/366
See issue
All passing
```
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
contracts/             |      100 |      100 |      100 |      100 |                |
Imports.sol           |      100 |      100 |      100 |      100 |                |
Index.sol             |      100 |      100 |      100 |      100 |                |
Indexer.sol           |      100 |      100 |      100 |      100 |                |
contracts/interfaces/  |      100 |      100 |      100 |      100 |                | …
```
=> Protocol in indexer

source/delegate/contracts/Delegate.sol
Added missing natspec line, pointed out by Quantstamp.
=> Added missing natspec line

source/swap/contracts/Swap.sol, source/swap/test/Swap.js
- Changes the affiliate check to be the token address
- Added a test where the affiliate is paid with an NFT
96 passing (12s)
=> Affiliate check

source/delegate/contracts/Delegate.sol, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js, source/indexer/contracts/Indexer.sol, source/indexer/test/Indexer-unit.js, source/swap/contracts/Swap.sol, source/swap/test/Swap-unit.js, source/swap/test/Swap.js, source/transfers/contracts/handlers/ERC20TransferHandler.sol, source/transfers/contracts/handlers/ERC721TransferHandler.sol, source/transfers/contracts/handlers/KittyCoreTransferHandler.sol, source/transfers/test/TransferHandlerRegistry.js, source/wrapper/test/Wrapper.js, utils/pre-swap-checker/contracts/PreSwapChecker.sol, utils/pre-swap-checker/test/PreSwapChecker.js
Formatting remaining reasons approximately as `NOUN_ADJECTIVE`.
=> Updating revert reasons for consistency

source/swap/contracts/Imports.sol, source/swap/test/Handlers.js, source/transfers/contracts/Imports.sol, source/transfers/package.json, source/transfers/test/TransferHandlerRegistry.js
Removed many imports from Imports.sol including Swap, Delegate, Indexer, ....
Added back handler specific tests related to Swap back to the Swap repo
Reduced number of tests to 26
Still 100% in all the handlers and token registry. Swap coverage will test the different cases within swap now.
```
26 passing (7s)
-------------------------------|----------|----------|----------|----------|----------------|
File                           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------|----------|----------|----------|----------|----------------|
contracts/                    |      100 |      100 |      100 |      100 |                |
Imports.sol                  |      100 |      100 |      100 |      100 |                | …
```
=> Remove swap dependency in the transfers repo

source/swap/package.json, source/tokens/package.json, source/transfers/package.json, source/types/package.json, source/wrapper/package.json, utils/deployer/package.json, utils/order-utils/package.json, utils/pre-swap-checker/package.json
=> Bumping tokens to 1.0.4

utils/deployer/migrations/1_initial_migration.js
We also need to deploy contract created contracts such that they can be verified through etherscan later.
Added the Index to deployment
Deployed and Verified with:
```
yarn migrate --network mainnet; yarn verify Index flatten/Flattened.sol --network mainnet
```
=> Add Index Verification

utils/pre-swap-checker/contracts/Imports.sol, utils/pre-swap-checker/contracts/Migrations.sol, utils/pre-swap-checker/contracts/PreSwapChecker.sol, utils/pre-swap-checker/package.json, utils/pre-swap-checker/test/PreSwapChecker.js
Add additional checks on pre-swap-checker to reflect token-registry and differentiate between erc20 and erc721. 
26 passing (24s)
```
---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
contracts/          |      100 |      100 |      100 |      100 |                |
Imports.sol        |      100 |      100 |      100 |      100 |                |
PreSwapChecker.sol |      100 |      100 |      100 |      100 |                |
---------------------|----------|----------|----------|----------|--------- …
```
=> Update swap registry

utils/pre-swap-checker/contracts/Imports.sol, utils/pre-swap-checker/contracts/PreSwapChecker.sol, utils/pre-swap-checker/package.json, utils/pre-swap-checker/test/PreSwapChecker.js
Added additional checks for using the wrapper
32 passing (48s)
---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
contracts/          |      100 |      100 |      100 |      100 |                |
Imports.sol        |      100 |      100 |      100 |      100 |                |
PreSwapChecker.sol |      100 |      100 |      100 |      100 |                |
---------------------|----------|----------|----------|----------|----------------|
All files            |      100 |      100 |      100 |      100 |                | …
=> Wrapper swap checker

CONTRIBUTING.md, SOLIDITY_STYLE_GUIDE.md
Adding a quick contribution.md #250 
Adding a contributor guide for more information on getting started and using the repo.
N/A
N/A
=> Add contributors

source/delegate/package.json, source/indexer/package.json, source/swap/package.json, source/transfers/package.json, source/types/package.json, source/wrapper/package.json, utils/debugger/package.json, utils/deployer/package.json, utils/order-utils/package.json, utils/pre-swap-checker/package.json
=> remove beta flag from versions

.circleci/config.yml, tools/order-utils/package.json, tools/test-utils/package.json
Adds `clients`, `constants`, and `utils` packages.
=> Adding new packages to circleci NPM publishing steps

.circleci/config.yml, tools/debugger/src/check-order.js, tools/debugger/test/check-order.js
- Separated ERC721 and Cryptokitties in script
- Added ERC1155 checks
- Added tests for all of the above
18 passing (17s)
=> Finalise debugger

tools/utils/package.json, yarn.lock
Adding `ethereumjs-abi` and `ethereumjs-util` to `@airswap/utils`
=> Adding missing deps from @airswap/utils

tools/protocols/src/Delegate.ts
Introduces a common `getQuotedOrMaxAvailable` to return quotes based on balance available. Implemented in `getMaxQuote`, `getSenderSideQuote`, and `getSignerSideQuote`
=> Check delegate balance

source/indexer/package.json, source/swap/package.json, source/types/index.ts, source/types/package.json, tools/constants/package.json, tools/deployer/package.json, tools/pre-swap-checker/package.json, tools/protocols/package.json, tools/protocols/src/Delegate.ts, tools/protocols/src/Server.ts, tools/protocols/src/Swap.ts, tools/utils/index.ts, tools/utils/package.json, tools/utils/src/orders.ts
* Updates Order type to include signature
* Introduces UnsignedOrder type
* Updates sorting utils to accept arrays of Quote or Order
=> Update order type and sorting utils

package.json, scripts/dependency_checker.py
* Includes dep checker in pre-commit hook
* Updates checker to only print violations
=> Update dependency checker

source/indexer/package.json, source/swap/package.json, source/types/index.ts, source/types/package.json, tools/constants/package.json, tools/deployer/package.json, tools/pre-swap-checker/package.json, tools/protocols/package.json, tools/protocols/src/Delegate.ts, tools/protocols/src/Indexer.ts, tools/utils/index.ts, tools/utils/package.json
* Adds optional `protocol` and `locator` to `Quote` type
* Includes `protocol` and `locator` on `Delegate` client quotes
* Adds `getAddress` function to Indexer client
=> Adding protocol and locator to Quote type

tools/utils/src/hashes.ts, tools/utils/src/orders.ts
* Correct signOrder to take an UnsignedOrder
* Rename verifyingContract to swapContract
=> Correct type for signOrder and rename verifyingContract

tools/utils/index.ts, tools/utils/package.json
* Adding two additional getBest* functions
* Adding getEtherscanURL function
=> Additional Utils

yarn.lock
Updating to account for the manual upgrade to mocha@7.0.1.
=> Updating yarn.lock with recent additions

source/validator/test/SwapValidator.js, tools/test-utils/src/balances.js
=> Update balance erc1155

tools/deployer/contracts/Imports.sol
=> Validator deploy

.circleci/config.yml, source/delegate/package.json, source/indexer/package.json, source/swap/package.json, source/transfers/package.json, source/validator/package.json, source/wrapper/package.json, tools/constants/index.ts, tools/constants/package.json, tools/debugger/src/check-order.js, tools/deployer/package.json, tools/metadata/package.json, tools/order-utils/src/signatures.js, tools/protocols/package.json, tools/protocols/src/Server.ts, tools/protocols/test/Server.test.ts, tools/test-utils/index.js, tools/test-utils/package.json, tools/test-utils/src/balances.js, tools/utils/index.ts, tools/utils/package.json, tools/utils/src/orders.ts, tools/utils/src/quotes.ts, tools/utils/test/orders.ts, tools/utils/test/quotes.ts, yarn.lock
* Adds validation to Server client
* Adds Server client tests
* `TODO`: Add tests for remaining clients
=> Adds validation and tests for Server

source/delegate/package.json, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js, source/indexer/package.json, source/swap/package.json, source/swap/test/Swap.js, source/tokens/package.json, source/transfers/package.json, source/types/index.ts, source/types/package.json, source/types/test/Types-unit.js, source/validator/package.json, source/wrapper/package.json, source/wrapper/test/Wrapper-unit.js, source/wrapper/test/Wrapper.js, tools/constants/index.ts, tools/constants/package.json, tools/deployer/package.json, tools/metadata/package.json, tools/protocols/package.json, tools/protocols/test/Server.test.ts, tools/test-utils/package.json, tools/utils/package.json, tools/utils/src/orders.ts, tools/utils/src/quotes.ts
* Remove dep cycle types -> constants -> types
* Only publishes new constants and types packages
=> Remove dep cycle between constants and types

package.json, tools/protocols/test/Delegate.test.ts, tools/protocols/test/ERC20.test.ts, tools/protocols/test/Indexer.test.ts, tools/protocols/test/Server.test.ts, tools/protocols/test/Swap.test.ts, tools/protocols/test/Validator.test.ts
Adds tests for `@airswap/protocols` clients.
=> Mock protocols

tools/metadata/index.ts, tools/metadata/package.json, tools/metadata/src/constants.ts, tools/metadata/src/helpers.ts
Now tokens can be dynamically fetched for any testnet, and NFTs are supported on mainnet & goerli.
=> added testnet support to fetchToken in metadata

source/delegate/contracts/DelegateV2.sol
=> Natspec delegate v2

subgraph/config/goerli.json, subgraph/config/kovan.json, subgraph/config/rinkeby.json
Generic update of subgraph configs so that different deployments can be managed with 
`yarn prepare:development`
`yarn prepare:mainnet`
`yarn prepare:rinkeby`
`yarn prepare:kovan`
`yarn prepare:goerli`
=> Update Subgraph Configs

source/delegate/contracts/DelegateV2Factory.sol, source/delegate/test/Delegate-V2-Factory-unit.js
- Delegatev2Factory
- unit tests for the factory 
4 passing (3s)
```
188 passing (17m)
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
contracts/             |      100 |      100 |      100 |      100 |                |
Delegate.sol          |      100 |      100 |      100 |      100 |                |
DelegateFactory.sol   |      100 |      100 |      100 |      100 |                |
DelegateV2.sol        |      100 |      100 |      100 |      100 |                |
DelegateV2Factory.sol |      100 |      100 |      100 |      100 |                | …
```
=> Delegate v2 factory

tools/subgraph/AirSwap.postman.json, tools/subgraph/schema.graphql, tools/subgraph/src/DelegateFactoryMapping.ts, tools/subgraph/src/DelegateMapping.ts, tools/subgraph/src/EntityHelper.ts, tools/subgraph/src/IndexMapping.ts, tools/subgraph/src/IndexerMapping.ts, tools/subgraph/src/SwapMapping.ts
Adding block numbers to `ExecutedOrders` as it will allow us to properly alert of trades from the Block Cruncher Service
https://github.com/airswap/block-data-cruncher/pull/26
=> Add Block Number and Update Entity Namings

tools/subgraph/schema.graphql, tools/subgraph/src/SwapMapping.ts
```
{
"data": {
"swaps": [
{
"block": "105",
"id": "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c11588607085498",
"transactionHash": "0x3931acb477324ad268e82802458e9e803d9d1291ce9da57af32d94cd8d661c0d"
},
{
"block": "113",
"id": "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c11588607087115",
"transactionHash": "0x5509af513655f65008be63824e7760680c84bb3713e50b5e63fecf97e4687bb9"
},
...
```
=> Add Transaction Hash to Swap Entity

source/delegate/package.json, source/swap/package.json, source/validator/package.json, source/wrapper/package.json, tools/protocols/package.json, tools/utils/package.json, tools/utils/src/orders.ts
=> Fixing parsing function for big numbers

source/delegate/package.json, source/swap/package.json, source/validator/package.json, source/wrapper/package.json, tools/protocols/package.json, tools/utils/package.json, tools/utils/src/orders.ts
tested on:
```
0xc7d26c8600000000000000000000000000000000000000000000000000000171d1a23e8b000000000000000000000000000000000000000000000000000000005eac815336372b0700000000000000000000000000000000000000000000000000000000000000000000000000000000442603794bdbfcc88f2efa1bce7a6caec3e34ad9000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000016345785d8a0000000000000000000000000000000000000000000000000000000000000000000036372b070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006fe56c0bcdd471359019fcbc48863d6c3e9d4f410000000000000000000000000000000000000000000000106cf83ea31f5c0000000000000000000000000000000000000000000000000000000000000000000036372b0 …
```
=> improvement to parse function

tools/protocols/package.json, tools/protocols/src/Server.ts
=> Use jayson browser client if in browser

tools/protocols/package.json, tools/protocols/src/Delegate.ts
Discussion between ejwessel and Matt JSON in Discord:
=> Update Delegate.ts getQuotedOrMaxAvailable() against trade wallet

tools/subgraph/schema.graphql, tools/subgraph/src/SwapMapping.ts
=> Update the swap entity field

source/locker/contracts/Imports.sol, source/locker/contracts/Locker.sol, source/locker/package.json, source/locker/test/Locker-unit.js, source/locker/test/Locker.js, yarn.lock
Coverage
```
Imports.sol |      100 |      100 |      100 |      100 |                |
Locker.sol  |      100 |      100 |      100 |      100 |                |
All files     |      100 |      100 |      100 |      100 |                |
```
=> Locker Unit Tests

source/pool/contracts/Imports.sol, source/pool/contracts/Pool.sol, source/pool/package.json, source/pool/test/Pool-unit.js, yarn.lock
Coverage
```
Imports.sol |      100 |      100 |      100 |      100 |                |
Pool.sol    |      100 |      100 |      100 |      100 |                |
All files     |      100 |      100 |      100 |      100 |                |
```
=> Pool Unit Tests

tools/subgraph/AirSwap.postman.json, tools/subgraph/abis/Delegate.json, tools/subgraph/abis/DelegateFactory.json, tools/subgraph/abis/Index.json, tools/subgraph/abis/Indexer.json, tools/subgraph/abis/Light.json, tools/subgraph/abis/Locker.json, tools/subgraph/abis/Pool.json, tools/subgraph/abis/Swap.json, tools/subgraph/config/mainnet.json, tools/subgraph/schema.graphql, tools/subgraph/src/EntityHelper.ts, tools/subgraph/src/LockerMapping.ts, tools/subgraph/src/PoolMapping.ts, tools/subgraph/src/SwapLightMapping.ts, tools/subgraph/src/SwapMapping.ts, tools/subgraph/subgraph.template.yaml
=> Subgraph: Light, Locker, Pool

source/staking/contracts/Imports.sol, source/staking/contracts/Staking.sol, source/staking/package.json, source/staking/test/Staking-unit.js, source/staking/test/Staking.js
Adds ERC-20 properties and events
Fixes a bug with `vested` function
Fixes a bug with `availableToUnstake` function
Restores `addToStakeFor` logic
=> AIP 17 updates

source/staking/hardhat.config.js, source/staking/scripts/staking-deploy.js
=> Deploy and Verify Staking

source/staking/test/Staking-unit.js
=> Add missing extendFor tests

tools/subgraph/config/bsc.json, tools/subgraph/package.json
updates to template and configs for AirSwap BSC Subgraph
=> AirSwap BSC

tools/subgraph/config/mainnet.json
=> Update Light Subgraph

tools/subgraph/abis/Light.json, tools/subgraph/schema.graphql, tools/subgraph/src/SwapLightMapping.ts, tools/subgraph/subgraph.template.yaml
=> Update Subgraph Light Logic and ABI

source/registry/contracts/Registry.sol, source/registry/test/Registry-unit.js
=> Small Fixes to Registry

source/registry/hardhat.config.js, source/registry/package.json, yarn.lock
```
Registry Unit
Default Values
✓ constructor set default values (72ms)
Add Tokens
✓ add an empty list of tokens fails (75ms)
✓ add a list of tokens when there is sufficient stake token (571ms)
✓ add a list of tokens when there is insufficent stake token (555ms)
✓ add a list of duplicate tokens fails (171ms)
✓ add a duplicate token (264ms)
Remove Tokens
✓ remove an empty list of tokens fails
✓ remove a list of tokens (360ms)
✓ remove all tokens for a staker fails when there are no tokens to remove
✓ remove all tokens for an staker (384ms)
✓ remove a list of duplicate tokens fails (180ms)
✓ remove a token already removed fails (315ms)
Set Locator
✓ successful setting of locator (39ms)
✓ successful changing of locator, check by staker (41ms)
✓ successful changing of locator, check by token …
```
=> Registry Coverage

source/registry/package.json
This pulls my upstream optimizations to EnumerableSet and EnumerableMap.
See [changelog](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md#420-2021-06-30).
Reviewers @dmosites @ejwessel
=> OpenZeppelin 4.2.0

tools/metadata/index.ts, tools/metadata/package.json, tools/metadata/test/metadata.ts, yarn.lock
Return a `message` and `url` for errors; remove AST check in tests
=> @airswap/metadata: error handling

source/light/README.md, source/wrapper/.npmignore, source/wrapper/LICENSE, source/wrapper/README.md, source/wrapper/contracts/Wrapper.sol, source/wrapper/contracts/interfaces/IWETH.sol, source/wrapper/deploys.js, source/wrapper/hardhat.config.js, source/wrapper/package.json, source/wrapper/scripts/deploy.js, source/wrapper/test/unit.js
Wraps `swapWithRecipient` function of `@airswap/light` to automatically wrap and unwrap WETH if it's sent or received during a swap. Requires that the `senderWallet` of an order is set to the wrapper contract address.
=> New wrapper

source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol, source/wrapper/contracts/Wrapper.sol, source/wrapper/package.json, source/wrapper/test/integration.js, source/wrapper/test/unit.js
Fixed setSwapContract to zero out allowance when new address is set.
Added sellNFT and buyNFT functions to wrapper contract.
=> Fix wrapper swapContract setter, add sellNFT and buyNFT to wrapper

source/pool/contracts/Pool.sol, source/pool/contracts/interfaces/IPool.sol, source/pool/test/unit.js
#747 add withdrawWithSignature function. Edited IPool.sol, Pool.sol and unit.js files.
=> Add withdrawWithSignature function

source/registry/test/unit.js, source/wrapper/test/unit.js
#749 
Improve test coverage for wrapper and registry contract to 100%
=> Test coverage for wrapper and registry

source/pool/package.json, source/registry/package.json, source/swap/package.json, source/wrapper/package.json, tools/libraries/package.json, tools/utils/index.ts, tools/utils/package.json
Extra little helper I thought was useful while implementing the new mobile design.
=> Added getEtherscanWalletURL helper

tools/subgraph/config/mainnet.json, tools/subgraph/package.json, tools/subgraph/subgraph.template.yaml
=> update subgraph with latest wrapper contract

source/wrapper/contracts/Wrapper.sol, source/wrapper/test/integration.js, source/wrapper/test/unit.js
PVE002-3: Removal of Unused State / Code #779
=> Remove requirement and payable keyword for sellNFT

source/staking/contracts/Staking.sol
PVE002-2: Removal of Unused State / Code #778
=> Removal of unused state variables 

source/staking/contracts/Staking.sol
PVE004: Accommodation of Non-ERC20-Compliant Tokens #781
=> accommodation of non-erc20-compliant token

source/pool/contracts/Pool.sol, source/pool/contracts/interfaces/IPool.sol
Add uint256 score to Withdraw event for Pool #792
=> Add score to Withdraw event

source/pool/contracts/Pool.sol
PVE002: Improved Logic of Pool:withdrawAndStakeFor() #777
=> Remove approve statement in withdrawAndStakeFor function

source/pool/contracts/Pool.sol, source/pool/contracts/interfaces/IPool.sol, source/pool/test/integration.js, source/pool/test/unit.js, tools/typescript/index.ts, tools/utils/index.ts, tools/utils/test/utils.ts, yarn.lock
Updated pool contract, tests, and repo's typescript/utils to include expiry in pool claims.
=> Add expiry to pool claim

source/swap/contracts/Swap.sol
changes
- refactored domain_typehash and order_typehash
=> swap audit 3.4

source/swap-any/contracts/SwapAny.sol, source/swap-any/contracts/TransferHandlerRegistery.sol, source/swap-any/contracts/handlers/ERC1155TransferHandler.sol, source/swap-any/contracts/handlers/ERC20TransferHandler.sol, source/swap-any/contracts/handlers/ERC721TransferHandler.sol, source/swap-any/contracts/handlers/KittyCoreTransferHandler.sol, source/swap-any/contracts/interfaces/ISwapAny.sol, source/swap-any/contracts/interfaces/ITransferHandler.sol
Address issue #925 https://github.com/airswap/airswap-protocols/issues/925
=> Created swap-any directory and imported swap v2 files

source/swap/contracts/Swap.sol, source/swap/contracts/handlers/ERC1155TransferHandler.sol, source/swap/contracts/handlers/ERC20TransferHandler.sol, source/swap/contracts/handlers/ERC721TransferHandler.sol, source/swap/contracts/interfaces/ISwap.sol, source/swap/contracts/interfaces/ITransferHandler.sol, source/swap/test/unit.js
Adjusting protocol fees to match swap-erc20
Fixes issue #928
=> Protocol fee update

source/swap/contracts/handlers/ERC777TransferHandler.sol, source/swap/test/unit.js, tools/constants/index.ts
=> Add erc777handler

source/indexer-registry/package.json, source/maker-registry/package.json, source/pool/package.json, source/staking/package.json, source/swap-erc20/package.json, source/swap/contracts/Swap.sol, source/swap/contracts/handlers/ERC1155TransferHandler.sol, source/swap/contracts/handlers/ERC20TransferHandler.sol, source/swap/contracts/handlers/ERC721TransferHandler.sol, source/swap/contracts/handlers/ERC777TransferHandler.sol, source/swap/contracts/interfaces/ISwap.sol, source/swap/contracts/interfaces/ITransferHandler.sol, source/swap/test/ERC777TransferHandler.js, source/swap/test/Swap.js, source/wrapper/package.json, yarn.lock
Pending integration of approval mechanism
=> First wave of audit remediation recommendations

source/swap-erc20/contracts/SwapERC20.sol, source/swap-erc20/contracts/interfaces/ISwapERC20.sol, source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol, source/swap/test/Swap.js, source/wrapper/contracts/Wrapper.sol, source/wrapper/test/unit.js, tools/libraries/src/Wrapper.ts, tools/typescript/index.ts, tools/utils/src/swapERC20.ts
=> Wrapper support for Swap and SwapERC20

packages/swap-erc20/contracts/SwapERC20.sol, packages/swap/contracts/Swap.sol, packages/wrapper/contracts/Wrapper.sol
Requires additional tests. API here:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/49c0e4370d0cc50ea6090709e3835a3091e33ee2/contracts/access/Ownable2Step.sol
=> Use Ownable2Step for Swap, SwapERC20, Wrapper

packages/swap/contracts/Swap.sol, packages/swap/contracts/adapters/ERC1155Adapter.sol, packages/swap/contracts/adapters/ERC20Adapter.sol, packages/swap/contracts/adapters/ERC721Adapter.sol, packages/swap/contracts/adapters/ERC777Adapter.sol, packages/swap/package.json, yarn.lock
=> update to @openzeppelin/contracts; remove redundant domain hash

packages/swap-erc20/contracts/SwapERC20.sol, packages/swap-erc20/contracts/interfaces/ISwapERC20.sol, packages/swap-erc20/package.json, packages/swap-erc20/test/unit.js, packages/swap/contracts/Swap.sol, packages/swap/contracts/interfaces/ISwap.sol, packages/swap/package.json, packages/swap/test/Swap.js, packages/wrapper/package.json, yarn.lock
Closes #1030 #1031 #1039 
Upgrades @airswap/utils to 4.0.0-beta.1
=> Terminology; version; config

tools/libraries/package.json, yarn.lock
* missing packages for libraries
* bump package version for publishing
* beta package for swap
=> update library deps (#1099)

source/pool/contracts/Pool.sol, source/pool/test/Pool.js, source/pool/test/PoolIntegration.js, source/registry/contracts/Registry.sol, source/registry/test/unit.js
Double checked invariants tests.
Added Integration tests for the pool
=> Audit prep

tools/libraries/src/Contracts.ts, tools/libraries/src/Server.ts, tools/utils/src/pricing.ts, tools/utils/src/swapERC20.ts, tools/utils/test/utils.ts
`isValidPricingERC20Pair` checks the first level of the first ask.
=> pricing validation util; adjustments to libraries

tools/libraries/src/Server.ts, tools/libraries/test/Server.test.ts, tools/utils/src/pricing.ts
Also improve order response handling.
=> Add pricing verification to server library

source/pool/package.json, tools/metadata/package.json, tools/metadata/tokenlists.ts
update `@airswap/metadata` to `4.1.8`
=> add tokenlists for telos evm mainnet, testnet

source/pool/package.json, source/swap-erc20/package.json, source/swap/package.json, source/wrapper/package.json, tools/libraries/package.json, tools/libraries/src/Server.ts, tools/libraries/test/Server.test.ts, tools/metadata/package.json, tools/types/package.json, tools/types/src/server.ts, tools/utils/package.json
Update types and server library to reflect Indexing spec.
=> indexing updates to types and server library

source/batch-call/package.json, source/pool/package.json, source/registry/package.json, source/staking/package.json, source/swap-erc20/package.json, source/swap/package.json, source/wrapper/package.json, tools/libraries/package.json, tools/stores/LICENSE, tools/stores/README.md, tools/stores/index.ts, tools/stores/package.json, tools/stores/redis/redis.config.ts, tools/stores/redis/redis.init.js, tools/stores/redis/redis.ts, tools/stores/test/redis.ts, tools/stores/tsconfig.json, tools/utils/package.json, tools/utils/src/constants.ts, yarn.lock
The stores package provides backends for Indexing servers.
The initial backend is Redis.
=> Add stores package
