protocols/peer/README.md, protocols/peer/contracts/Peer.sol, protocols/peer/interfaces/IPeer.sol, protocols/swap/MIGRATION.md, protocols/swap/README.md
Peers are no longer payable because `Swap` is not payable.
Updating `Peer`, `IPeer`, and documentation.
=> Removing unnecessary payable keywords

protocols/indexer/contracts/Indexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/market/contracts/Market.sol, protocols/market/test/Market-unit.js, protocols/market/test/Market.js
Cleaning expired intents wasn't returning staked tokens to stakers. The cleaning function has been moved to the indexer, so that such unstaking happens.
- Market now has `findExpiredIntents` that returns an array of expired stakers
- Indexer has a `cleanExpiredIntents` function that calls `findExpiredIntents`, and then removes each of these staker's intents
- Pulled out common unstaking functionality from `unsetIntent` and `cleanExpiredIntents` into one function `removeIntent`
```
Indexer.sol |      100 |      100 |      100 |      100 |
Market.sol  |      100 | …
```
=> Expired intents bug

protocols/indexer/contracts/Indexer.sol
`removeIntent` was only called by `unsetIntent` within `Indexer`. This removes the extraneous internal method
=> Reduce Indexer Code

protocols/peer/test/Peer-unit.js
Correction of the calculations in peer tests, so that tests previously marked as `.skip` are run.
=> Unskip tests

protocols/indexer/contracts/Indexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/market/contracts/Market.sol, protocols/market/test/Market-unit.js
- Market is coupled to Indexer and intended to be used by the indexer. It is a specialized LL.
- The conditional check in Indexer that check if an intent exists and reverts should be placed into Market.
- Market will continue to sets intents by staker address. Additional logic will now exist if a staker tries to provide another intent, the staking will revert. This keeps with the old design.
- In order to update their intent a stake will need to first remove their old intent and then set a new intent
- Update the market so that if a sender were to stake another intent that it will fail. This logic is being moved out of indexer
- Update market and indexer tests to reflect these changes
- Write tests that ensure that the underlying linked list structure has not been compromised.
=> Update Market and Indexer Logic

helpers/wrapper/contracts/Wrapper.sol, helpers/wrapper/test/Wrapper-unit.js
Added a require to ensure on non-WETH trxn the taker wallet is the msg.sender. Prevents another user filling on behalf of the wrapper.
```
27 Passing
Imports.sol |      100 |      100 |      100 |      100 |                |
Wrapper.sol |      100 |      100 |      100 |      100 |                |
All files     |      100 |      100 |      100 |      100 |                | …
```
=> add require checking takers

examples/consumer/contracts/Consumer.sol, examples/consumer/test/Consumer-unit.js, protocols/peer/README.md, protocols/peer/contracts/Peer.sol, protocols/peer/contracts/interfaces/IPeer.sol, protocols/peer/test/Peer-unit.js, protocols/peer/test/Peer.js
- rename peerToken and consumerToken -> takerToken and makerToken 
- With the migration to swap, Peer needs to use swap instead.
- remove provideUnsignedOrder as now the function signatures are the same, the difference is whether Signature is populated or not 
- add require to ensure that order.maker.wallet is always msg.sender
- order.maker.kind and order.taker.kind are 0x277f8169 (ERC-20)
=> Migrating Peer from swapSimple to swap

examples/consumer/package.json, helpers/wrapper/package.json, packages/order-utils/package.json, packages/order-utils/src/orders.js, protocols/market/package.json, protocols/peer/package.json, protocols/swap/package.json
getOrder was adding an empty `signature` every time.
=> Quick fix for order-util

examples/consumer/test/Consumer.js, protocols/index/contracts/Index.sol, protocols/index/test/Index-test.js, protocols/index/test/Index-unit.js, protocols/indexer/contracts/Indexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/indexer/test/Indexer.js
Remove use of intent and instead use locator
From the viewpoint of the indexer, it should work with intents
Only the internal contract index works with locators
Locators are the name of the struct but the actual locator address/bytes32 is stored in the data field
Make sure REVERT_REASON use SIGNAL and not ENTRY
#Test 
Tests all pass with 100% coverage
=> Terminology update for Index and Signal

examples/consumer/contracts/Consumer.sol, helpers/tokens/contracts/interfaces/IWETH.sol, helpers/wrapper/contracts/Wrapper.sol
replaces all `^0.5.10` to `0.5.10`
```
grep -rl $(find * -name '*.sol') -e "\^0.5.10" | xargs sed -i ".bak" -e "s/\^0.5.10/0.5.10/g"
```
=> Update Pragma Float to strict 0.5.10

helpers/tokens/contracts/KittyCore.sol, helpers/tokens/contracts/OMGToken.sol
Add in nonstandard ERC20 and ERC721
Code was pulled from Etherscan and then upgraded to 0.5.10x.
The goal was to ensure that these files with slightly different transferFrom function can be tested to ensure Swap works with real-world tokens.
=> add non-standard token examples

helpers/delegate-frontend/contracts/DelegateFrontend.sol, packages/order-utils/src/constants.js, packages/order-utils/src/hashes.js, packages/order-utils/test/signatures.js, protocols/swap/test/Swap-unit.js, protocols/types/contracts/Types.sol
Quick description: 
Updated struct for Party and Signature.
Two primary changes in Types.sol that resulted in Party struct and Signature struct to have the below ordering. Longer explanation found in #150. 
```
struct Party {
bytes4 kind;          // Interface ID of the token
address wallet;       // Wallet address of the party
address token;        // Contract address of the token
uint256 param;        // Value (ERC-20) or ID (ERC-721)
}
struct Signature {
address signatory;    // Address of the wallet used to sign
bytes1 version;       // EIP-191 signature version
uint8 v;              // `v` value of an ECDSA signature
bytes32 r;            // `r` value of an ECDSA signature
bytes32 s;            // `s` value of an ECDSA signature
}
```
All tests pass
For Types.sol
``` …
```
=> restructing of the structs, to close #150

helpers/delegate-frontend/contracts/DelegateFrontend.sol, helpers/delegate-frontend/test/DelegateFrontend.js, helpers/wrapper/test/Wrapper.js, protocols/delegate/test/Delegate.js, protocols/swap/contracts/Swap.sol, protocols/swap/contracts/interfaces/ISwap.sol, protocols/swap/test/Swap-unit.js, protocols/swap/test/Swap.js
Implements features described in #156 to add two separate mappings for sender and signer.
* Adding two mappings `senderAuthorizations` and `signerAuthorizations`
Added 4 new methods and events:
* `authorizeSender`, `authorizeSigner`, `revokeSender`, `revokeSigner`.
* `AuthorizeSender`, `AuthorizeSigner`, `RevokeSender`, `RevokeSigner`
Swap.sol
66 passing (56s)
Also fixed Delegate, Delegate-Frontend, and Wrapper tests.
```
Imports.sol |      100 |      100 |      100 | …
```
=> Separate approvals

helpers/wrapper/contracts/Wrapper.sol
This line of the wrapper is seemingly useless.
- During a trade the wrapper gives the tokens to the order.sender.
- This means the tokens are swapped out of the sender's wallet not the wrapper
- The swap contract therefore never needs to move tokens out of the wrapper itself.
33 passing (5s)
=> unused wrapper line

helpers/delegate-frontend/contracts/DelegateFrontend.sol, helpers/delegate-frontend/test/DelegateFrontend-unit.js, helpers/delegate-frontend/test/DelegateFrontend.js, package.json, protocols/delegate-factory/contracts/DelegateFactory.sol, protocols/delegate-factory/test/Delegate-Factory-unit.js, protocols/delegate/contracts/Delegate.sol, protocols/delegate/test/Delegate-unit.js, protocols/delegate/test/Delegate.js, protocols/index/contracts/Index.sol, protocols/index/test/Index-unit.js, protocols/indexer/contracts/Indexer.sol, protocols/indexer/contracts/interfaces/IIndexer.sol, protocols/indexer/test/Indexer-unit.js, protocols/indexer/test/Indexer.js, protocols/types/contracts/Types.sol
API pass, cleanup, full eslint and solhint pass.
Updates to `Index.sol`:
1. Remove traces of "user" and replace with "identifier"
2. Update API to work with locators only. Consider an "Entry" to be an implementation detail
3. Remove references to "linked list"
4. `getEntry` becomes `getScore` and only returns score
5. Add a `require` to `unsetLocator` to throw if locator does not exist
Updates to `Indexer.sol`:
1. `getIntents` becomes `getLocators`
2. `stakeToken` becomes `stakingToken`
3. `Indexer.getScore becomes` becomes `Indexer.getStakeAmount`
4. Adds recent `Indexer.sol` additions to `IIndexer.sol` interface
=> Indexer and Index API and syntax cleanup

protocols/delegate/contracts/Delegate.sol
Making the trade wallet public, and removing the getter function. This saves gas deploying the contract.
=> public trade wallet with no getter

source/delegate/contracts/Delegate.sol, source/delegate/test/Delegate-unit.js
https://github.com/airswap/airswap-protocols/issues/213
- `setRuleAndIntent()` - added check that doesn't call `transferFrom()` with 0 staked amount
- `unsetRuleAndIntent()` - added check that doesn't call `transfer()` with 0 staked amount
```
70 passing (8s)
Delegate.sol         |      100 |      100 |      100 |      100 |                |
Imports.sol          |      100 |      100 |      100 |      100 |                |
contracts/interfaces/ | …
```
=> No Transfer call with 0 Stake

source/index/contracts/Index.sol, source/index/test/Index-unit.js, source/indexer/contracts/Imports.sol, source/indexer/contracts/Indexer.sol, source/indexer/contracts/interfaces/IIndexer.sol, source/indexer/test/Indexer-unit.js, source/indexer/test/Indexer.js, source/types/contracts/Types.sol
- Updated `setIntent` to allow stakes and locators to be updated without unsetting intent first. Discussed in issue https://github.com/airswap/airswap-protocols/issues/225.
- Added tests for this test case, as well as some more tests for the locatorWhitelist, as this was seemingly lacking in the integration tests previously.
90 passing (15s)
100%
=> Indexer update stake

source/delegate/contracts/Delegate.sol, source/delegate/test/Delegate.js
Noticed when doing documentation, this was the older function in delegate that had signerToken and then senderToken.
Full issue mentioned: https://github.com/airswap/airswap-protocols/issues/254
- [X ] Typo/small tweaks
Switch the ordering of inputting token addresses to unsetRuleAndIntent 
100%
100%
=> update ordering of unsetRuleAndIntent

source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json
This annoyed me:
```
mkdir src
mkdir: src: File exists
```
so I added the -p flag to reduce output and remove the error
```
mkdir -p src
```
from mkdir -p flag man page
> Create intermediate directories as required.  If this option is not specified, the full path prefix of each operand must already exist.  On the other hand, with this option specified, no error will be reported if a directory given as an operand already exists.  Intermediate directories are created with permission bits of rwxrwxrwx (0777) as modified by the current umask, plus write and search permission for the owner.
=> Remove mkdir output for already created dir

source/wrapper/contracts/HelperMock.sol, source/wrapper/contracts/Wrapper.sol, source/wrapper/test/Wrapper.js
https://github.com/airswap/airswap-protocols/issues/298
- Added a revert statement when ETH fails to send to a non-payable contract in the wrapper
- Created a mock contract that is non-payable to test this new revert
- Added an integration test that uses the new mock to test the revert
```
Wrapper:
39 passing (10s)
```
=> Revert if ETH return is unsuccessful

source/indexer/test/Indexer-unit.js
Updated the spelling on a test message where transfer was spelling incorrectly.
130 passing (28s)
=> Resolve spelling of test message

source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol, source/swap/test/Swap-unit.js, source/swap/test/Swap.js
Rename invalidate to cancelUpto
Put in a dev note to indicate that cancelUpto can be reversible in that it's not a hard cancel
All Passing
Just renaming and still at 100%
=> Rename invalidate to clearer term cancelUpTo

source/delegate/contracts/Delegate.sol, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js
https://github.com/airswap/airswap-protocols/issues/297
- Signers can now trade with any amount more than the going price. I.e. as long as the amount they send is at least the amount the delegate rule is expecting, its allowed.
- The signer side values in the contract now round up not down. This is in the delegate’s favour, and, combined with the point above, means quotes will then pass 
89 passing (1m)
```
Delegate.sol         | …
```
=> Delegate price bug

source/delegate/test/Delegate.js, source/indexer/test/Indexer.js, source/swap/test/Swap.js, source/wrapper/test/Wrapper.js
Removing snapshots from integration tests as truffle already does this/ This is a remnant from when lerna was set up differently.
=> Remove snapshots from integration tests

source/delegate/contracts/Delegate.sol, source/delegate/test/Delegate-unit.js, source/delegate/test/Delegate.js, source/swap/contracts/Swap.sol, source/swap/test/Swap-unit.js, source/swap/test/Swap.js, source/wrapper/test/Wrapper.js
Put in checks to ensure a state change was occurring before emitting events. Added some tests to ensure calling the functions duplicate times would not emit an event.
```
73 passing (15s)
lerna success run Ran npm script 'test' in 8 packages in 181.2s:
Done in 387.51s.
Still 100%
```
=> Remove throwing events for non-state changes in Swap and Delegate contract

.circleci/config.yml, package.json
https://github.com/airswap/airswap-protocols/issues/337
I wanted to be identify a failing test in parallel with other tests. The total time it takes for the circle job to pass is roughly a minute and a half faster*; lowers average time waiting for a test to be run.
*In some instances it's 50% faster
- [ X ] Typo/small tweaks
- circle ci script is updated to save the compiled state to a workspace and then all tests in parallel on that workspace.
- npm publish now requires all the tests to pass in order to deploy
=> Parallelize Circle

package.json, source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/wrapper/package.json, utils/deployer/package.json, utils/test-utils/package.json
When importing test-utils, and using its functions, the following error is thrown:
```
Error: Cannot find module 'ganache-time-traveler'
```
This is due to the fact it is a devDependency not a dependency
`test-utils` is the only module that uses this, so I have moved it into the `test-utils` repo.
=> moving ganache-time-traveller and bumping versions

README.md, utils/deployer/README.md
Small change to rename the guide to readme for the deployer package.
=> Renaming guide to readme for deployer package

package.json, source/delegate-factory/package.json, source/delegate/package.json, source/index/package.json, source/indexer/package.json, source/swap/package.json, source/types/package.json, source/wrapper/package.json, utils/deployer/package.json, utils/order-utils/package.json
- `order-utils` uses `ethereumjs-abi` which was previously a devDependency. The only reason we weren't hitting a problem of it being imported was because `eth-sig-util` imports it. Considering we use a carat for eth-sig I dont think we should rely on it being there forever. Have moved this dependency into `order-utils` and made it a `dependency`
- most repos were importing `solidity-coverage` independently. I moved it to be a global `devDependency`, seeing as this is where we import all of our other test-related packages.
=> Dependency revamp

source/swap/contracts/Swap.sol, source/swap/test/Swap.js
When we create trades on airswap trader we fill in the affiliate address so that we can track how many trades were originated by airswap. The token and amount are left as 0. This fails on the contracts as an empty affiliate was checked using `address(0)`.
=> Affiliate check of amount not address

source/indexer/contracts/Index.sol, source/indexer/contracts/Indexer.sol, source/indexer/test/Index-unit.js
Adding an update locator function to the index to avoid emitting `UnsetLocator` and `SetLocator` every time an update occurs.
- Common setLocator and unsetLocator logic pulled out into internal functions
- Index.updateLocator function added
- Index unit test for this function
106 passing (18s)
```
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
contracts/             |      100 |      100 |      100 |      100 |                |
Imports.sol           |      100 |      100 |      100 |      100 |                |
Index.sol             |      100 |      100 | …
```
=> Update locator function

source/delegate/package.json, source/indexer/package.json, source/swap/package.json, source/transfers/package.json, source/types/package.json, source/wrapper/package.json, utils/debugger/package.json, utils/debugger/src/check-order.js, utils/debugger/test/check-order.js, utils/deployer/package.json, utils/order-utils/package.json, utils/order-utils/src/orders.js, utils/order-utils/src/signatures.js, utils/order-utils/test/orders.js, utils/order-utils/test/signatures.js, utils/pre-swap-checker/package.json
- `orders.isValidOrder` now includes a call to `signatures.hasValidSignature`
- Adding tests to cover more variety of invalidity
=> Adding signature check and more tests to order-utils

source/swap/contracts/Swap.sol
Removed unused ERC721 constant given we now have a token registry. 
pass
pass
=> remove unused constant

source/delegate/package.json, source/delegate/test/Delegate.js, source/swap/contracts/Imports.sol, source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol, source/swap/package.json, source/wrapper/package.json, source/wrapper/test/Wrapper.js, utils/debugger/package.json, utils/pre-swap-checker/package.json
Realized we were missing `registry()` from `ISwap` when I was writing the `preSwapChecker` functions. I've added it as an external view in `ISwap` but continue to keep it was public in `Swap.sol`
- Added abstract function to ISwap.sol 
- Cleaned up `Imports.sol`
- Removed `TokenTransferRegistry` import from swap and added it to `ISwap`
- cleaned up an unused variables in `Delegate.js`
- some linting fixes were found in `Wrapper.js` 
- Updated `package.json` patch versions throughout
no change
no change
=> Add registry to ISwap interface

utils/pre-swap-checker/contracts/Imports.sol, utils/pre-swap-checker/contracts/PreSwapChecker.sol, utils/pre-swap-checker/package.json, utils/pre-swap-checker/test/PreDelegateChecker.js, utils/pre-swap-checker/test/PreSwapChecker.js
Put the preSwapDelegate check within the preSwapChecker
I separated the delegate tests into their own file as well (more forward looking for if we create a preSwapDelegateWrapper check function as well, i'll likely separate the smart contracts as well).
Added a prewap checker when using the delegate
46 passing (9s)
100%
=> add a delegate swap check

utils/clients/index.ts, utils/clients/package.json, utils/clients/src/Delegate.ts, utils/clients/src/ERC20.ts, utils/clients/src/Indexer.ts, utils/clients/src/Server.ts, utils/clients/src/Swap.ts, utils/clients/tsconfig.json, utils/constants/index.ts, utils/constants/package.json, utils/constants/tsconfig.json, utils/utils/index.ts, utils/utils/package.json, utils/utils/tsconfig.json
- Adds `@airswap/clients` containing JavaScript classes for protocol components including Swap, Indexer, Server, and Delegate. TODO: Complete remaining functionality for each component.
- Adds `@airswap/constants` to consolidate network constants into a single package. TODO: Merge more constants in from other packages.
- Adds `@airswap/utils` to consolidate JavaScript utilities into a single package. TODO: Merge more utility functions in from other packages.
=> Add `@airswap/clients` for JS Developers

tools/debugger/package.json
Empty compile script as the NPM deployer calls `compile` in every directory before deploying
=> adding empty compile script

tools/utils/src/quotes.ts, tools/utils/test/orders.ts, tools/utils/test/quotes.ts
Adds functions:
- `getTotalBySignerAmount` to sum up signer-side liquidity given a list of quotes
- `getTotalBySenderAmount` to sum up sender-side liquidity given a list of quotes
=> Add util functions to sum up quote values

.eslintrc.js, tools/protocols/package.json, tools/protocols/src/Delegate.ts, tools/protocols/src/ERC20.ts, tools/protocols/src/Indexer.ts, tools/protocols/src/Server.ts, tools/protocols/src/Swap.ts, tools/protocols/tsconfig.json
Includes `wallet` on delegate quotes, on the sender side, using the delegate tradeWallet. This allows a taker to pull down many quotes, sort to determine the best, and, given the best quote, to provide an order to the winning delegate.
=> Include wallet delegate quotes

source/indexer/package.json, source/swap/package.json, source/types/index.ts, source/types/package.json, tools/constants/index.ts, tools/constants/package.json, tools/deployer/package.json, tools/pre-swap-checker/package.json, tools/protocols/package.json, tools/protocols/src/Delegate.ts, tools/protocols/src/ERC20.ts, tools/protocols/src/Indexer.ts, tools/protocols/src/Swap.ts, tools/utils/package.json, tools/utils/src/hashes.ts, tools/utils/src/orders.ts, tools/utils/src/quotes.ts, tools/utils/test/quotes.ts
* QuoteParty requires `kind`, `token`, and `amount` or `id`
* OrderParty requires those and `wallet`
* Changed "signer" arguments to "wallet" to reduce confusion with protocol
=> Changes to Party types and syntax updates

tools/protocols/package.json, tools/protocols/src/Delegate.ts, tools/protocols/src/Server.ts, tools/utils/index.ts, tools/utils/package.json
* Adds util function to flatten an object into camelCase e.g. `order.signer.wallet` to `order.signerWallet`
* Uses this function in the Server client to compare results to corresponding requests
* E.g. if an amount is requested and the resulting order includes a lower or higher amount than requested an error is returned
* If a request param is not found in the response it is ignored because results are separately validated
=> Compare results to corresponding requests (Server)

.circleci/config.yml, .vscode/settings.json, tools/constants/index.ts, tools/constants/package.json, tools/metadata/README.md, tools/metadata/lib/constants.ts, tools/metadata/lib/index.ts, tools/metadata/package.json, tools/metadata/test/metadata.ts, tools/protocols/package.json, tools/utils/package.json, yarn.lock
* Renames `init` to `fetchKnownTokens` and `getToken` to `fetchToken`
* Adds simple tests to check `fetchKnownTokens` and `fetchToken`
* Syntax updates and readability
* Adds missing `@airswap/constants` dependency
=> Updates to @airswap/metadata

source/delegate/package.json, source/swap/package.json, source/validator/package.json, source/wrapper/package.json, tools/protocols/package.json, tools/utils/index.ts, tools/utils/package.json
Previously, when invoking a helper function such as `getBestByLowestSenderAmount(quotesArray)`, the helper would choke and throw an error when one of the quotes in the array was actually an error response. This presents an issue in the following workflow
1. We get all locators for a token pair
```
const { locators } = await new Indexer(chainIds.MAINNET).getLocators(signerToken, senderToken)
```
2. We iterate over these locators and request quotes.
```
const quotes = []
locators.forEach(async locator => {
const s = new Server(locator)
quotes.push(s.getSignerSideQuote(desiredAmountAtomic, signerToken, senderToken))
```
3. We use a helper to find the best quote
```
const bestQuote = getBestByLowestSenderAmount(quotes)
```
If one of the makers queried responds with an error or malformed …
=> ensure quote or order has lookup key defined before attempting to evaluate amount for comparison/sorting

source/delegate/package.json, source/indexer/package.json, source/swap/package.json, source/transfers/package.json, source/types/package.json, source/validator/package.json, source/wrapper/package.json, tools/constants/index.ts, tools/constants/package.json, tools/deployer/package.json, tools/metadata/index.ts, tools/metadata/package.json, tools/metadata/src/constants.ts, tools/metadata/src/types.ts, tools/protocols/package.json, tools/test-utils/package.json, tools/utils/package.json
This PR uses the OpenSea API to fetch ERC721 tokens and store them in the memory tokens store.
=> add support for ERC721 tokens in metadata package

tools/subgraph/schema.graphql, tools/subgraph/src/SwapMapping.ts
timestamp is missing on the swap
Add the timestamp on the swap entity.
```
{
"data": {
"swaps": [
{
"block": "116",
"id": "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c11588862034539",
"timestamp": "1494374850",
"transactionHash": "0x169413eea77aa34264840bfe873059327b973f37d28a79922371ac5db3263341"
},`
```
=> Add timestamp to swap entity

tools/metadata/index.ts, tools/metadata/package.json, tools/metadata/src/constants.ts, tools/metadata/test/metadata.ts
Adds a function to return all tokens sharing a symbol. For example:
```
await new TokenMetadata().fetchKnownTokens()
const DAI = metadata.findTokensBySymbol('DAI').shift()
```
=> Function to find token by symbol for @airswap/metadata

tools/metadata/index.ts, tools/metadata/package.json, tools/metadata/src/constants.ts, tools/metadata/src/types.ts
Changes to the `@airswap/metadata` package:
* IDEX asset URL has been updated
* IDEX response data format has been updated
* IDEX response is now an array
New URL: https://api.idex.io/v1/assets
=> Updating IDEX asset URL and response handler for @airswap/metadata

tools/metadata/README.md, tools/metadata/index.ts, tools/metadata/package.json, tools/metadata/src/helpers.ts, tools/metadata/test/metadata.ts
Updates `@airswap/metadata` to take an ethers provider instead of a chain ID.
This makes custom providers possible. Version updated from `0.1.11` to `0.2.0`.
=> Metadata providers

source/registry/contracts/Registry.sol, source/registry/hardhat.config.js, source/registry/package.json, source/registry/test/Registry-unit.js
* Caches AddressSet storage, saving linear amount of keccak map lookups
* Upgrades to latest solidity, 0.8.4
* Upgrades to latest openzeppelin-contracts, which needs solidity ^0.8.0
* Reversed removeAll order, fixing test and saving gas with https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2605
* Removes SafeMath, no-longer needed with solidity ^0.8.0
Reviewers @dmosites
=> Upgrade and Remove All Tokens in Reverse Order

tools/utils/index.ts, tools/utils/package.json
`parseUrl` takes a server locator and defaults it to `https` if neither http or https is specified.
This PR updates the test so that websocket locator urls aren't prepended with `https`. Required for #672
=> Add websocket support to parseUrl

tools/libraries/package.json, tools/libraries/src/Server.ts, tools/libraries/test/test-utils.ts
`0.0.1` never attempts to connect on node.
This was being covered up in the tests because the mock that was passed didn't have the same API as what it was meant to be mocking.
This PR should correct this.
=> Correct last look websocket node implementation

source/pool/test/unit.js, source/staking/test/unit.js
#749 Expand test coverage across existing contracts
Added more tests to Pool - unit.js and Staking - unit.js test files to improve coverage to 100%.
=> Improve test coverage for Pool and Staking contracts

source/converter/test/unit.js, source/swap/test/unit.js
Added additional tests to Converter contract unit test file and Swap contract unit test file.
Converter has 100% full test coverage.
Swap has 97.22% branch test coverage as a require statement is present that checks chain ID during signature verification in the event of a fork and change of chain ID. Was not able to find a way to configure change of chain ID within a test.
=> Converter swap coverage

source/converter/contracts/Converter.sol, source/converter/contracts/TokenPaymentSplitter.sol, source/pool/contracts/Pool.sol, source/pool/contracts/interfaces/IPool.sol, source/pool/package.json, source/pool/test/integration.js, source/pool/test/unit.js, source/staking/test/unit.js, source/swap/contracts/Swap.sol, source/swap/test/integration.js, source/swap/test/unit.js, source/wrapper/test/integration.js, source/wrapper/test/unit.js, tools/constants/index.ts, tools/typescript/index.ts, tools/utils/index.ts, tools/utils/test/utils.ts
Updated the pool contract to EIP712, and switched all withdraw functions to signature validation. Removed all merkle validation functionality. Updated tests, and updated tools (utils, typescript, constants) to include claim signatures and differentiate from order signatures.
=> Change pool withdraw functions to signatures, update tests and tools

source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol, source/swap/test/integration.js, source/swap/test/unit.js
Updated the fee rebate checker to check balanceOf within the staking contract, instead of just the staking token.
This will ensure senders cannot utilize flashloans to add the staking token to their account, as they would have to stake in the staking contract for a certain duration.
=> Fix swap staking balanceOf check to staking contract

source/converter/contracts/Converter.sol, source/converter/test/unit.js, source/pool/contracts/Pool.sol, source/pool/test/unit.js
Updated pool contract to use safeApprove. The reasoning to use this function instead of safeIncreaseAllowance & safeDecreaseAllowance is because we are only initializing an allowance to max approval value or resetting an existing allowance to zero, which aligns with the appropriate usage in the OpenZeppelin docs. Also, if we used safeDecreaseAllowance, then there may need to be an additional external call to get the current allowance.
Updated the converter contract to use safeIncreaseAllowance. The reasoning is that we never decrease the allowance, and even though the allowance should go back zero after going through the AMM doing this just to be extra safe.
=> Update approval to safeApproval and safeIncreaseAllowance

tools/libraries/package.json, tools/metadata/index.ts, tools/metadata/package.json
Fixes [#522 ](https://github.com/airswap/airswap-web/issues/522)
Fixed findTokenByAddress; token addresses can be both lower and uppercase.
=> 522: findTokenByAddress fix

source/pool/package.json, source/swap/package.json, source/wrapper/package.json, tools/libraries/package.json, tools/utils/index.ts, tools/utils/package.json
Usage:
```
import { getOrderHash } from '@airswap/utils';
getOrderHash(unsignedOrder, swapContract).toString('base64');
```
=> Adds order hashing to utils

source/pool/contracts/Pool.sol, source/pool/contracts/interfaces/IPool.sol, source/pool/test/integration.js, source/pool/test/unit.js
Consolidates Pool interface to only `withdraw` and `withdrawAndStake` functions, which both always take a `recipient` and `minimum` arguments.
=> Simplify pool interface

hardhat.config.js, source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol
Changes 
- Locked solidity version to 0.8.17 in both Swap.sol and ISwap.sol
- Changed solidity version in the hardhat config located at the root, from 0.8.7 to 0.8.17
=> Swap audit 3.1

source/swap/contracts/Swap.sol
Simplified _hashOrder function by encoding each party as a whole for better readability
=> Simplified _hashOrder function - fixes #992

packages/swap-erc20/contracts/SwapERC20.sol, packages/swap-erc20/contracts/interfaces/ISwapERC20.sol, packages/swap-erc20/test/unit.js, packages/swap/contracts/Swap.sol, packages/swap/contracts/interfaces/ISwap.sol, packages/swap/test/Swap.js
avoids possibility that signer and authorized signatory could sign the same order terms.
=> ensure that authorized signatory is used if one is set

tools/metadata/index.ts, tools/metadata/package.json, tools/types/src/typescript.ts, yarn.lock
Introduces functions `getTokenKind`, `getTokenInfo`, and `getCollectionTokenInfo` to fetch data from on-chain assets. In case of a `CollectionTokenInfo` with bad metadata, those fields are left blank except for name as "Unknown NFT".
=> CollectionTokenInfo for @airswap/metadata

.eslintrc, .prettierignore, source/pool/contracts/Pool.sol, source/pool/contracts/interfaces/IPool.sol, source/pool/test/Pool.js, source/registry/test/unit.js, source/staking/test/Staking.js, source/swap-erc20/test/SwapERC20.js
Staking is only on mainnet so removed from constructor.
Combined staking token and contract into single setter.
Removed unused mapping from previous implementation.
Includes latest from develop.
=> Pool: simplify constructor, staking; remove mapping

source/balances/package.json, source/pool/package.json, source/registry/package.json, source/swap-erc20/package.json, source/swap/package.json, source/wrapper/package.json, tools/constants/index.ts, tools/constants/package.json, tools/libraries/package.json, tools/metadata/package.json, tools/utils/package.json
on Linea, the staking token (usually AST) was set to WETH. the web app is looking for WETH by address and so ends up finding and using the staking token / AST. this PR temporarily updates the staking token to another ERC20 on Linea.
=> temp replacement for linea staking token

tools/constants/index.ts, tools/constants/package.json, tools/constants/test/utils.ts
Add `minExpiry` to RequestForQuoteERC20 functions.
Split LastLookERC20 into PricingERC20 and LastLookERC20 interfaces.
Add `chainId` and `swapContractAddress` to Storage interfaces.
=> update protocol interfaces and ids

tools/libraries/package.json, tools/libraries/src/Server.ts
Issue: When maker is having this kind of endpoint: https://marker.com/my_cutom_path
jayson is configured with only https://marker.com
=> fix(jayson): Fix url for maker when configuring jayson

source/swap/contracts/Swap.sol, source/swap/test/Swap.js
Allows check to be run on public orders with a yet unknown sender.
=> check sender allowance and balance only if sender is set

source/swap-erc20/contracts/SwapERC20.sol
Use `ERC20` for all `balanceOf` and `allowance` calls.
Use `SafeTransferLib` for all transfers.
=> @airswap/swap-erc20: use ERC20 for all balanceOf calls

source/delegate/contracts/Delegate.sol, source/delegate/contracts/interfaces/IDelegate.sol, source/delegate/deploys-blocks.js.d.ts, source/delegate/deploys.js.d.ts, source/delegate/package.json, source/delegate/test/Delegate.js, source/swap-erc20/contracts/SwapERC20.sol, source/swap-erc20/contracts/interfaces/ISwapERC20.sol, source/swap-erc20/test/SwapERC20.js, source/swap/contracts/Swap.sol, source/swap/contracts/interfaces/ISwap.sol
* Adds and updates comments.
* Updates Rule parameter names.
* Modifies errors for Delegate and SwapERC20.
* Modifies SetRule event.
=> Delegate and SwapERC20 Finalizations

source/delegate/contracts/Delegate.sol, source/delegate/contracts/interfaces/IDelegate.sol, source/delegate/test/Delegate.js
* Fixes incorrect signerAmount check
* Changes expiry check to `<=` to match SwapERC20
* Changes `RuleExpired` to `RuleExpiredOrDoesNotExist`
* Adds test and updates other related tests
=> Delegate Updates

source/delegate/contracts/Delegate.sol, source/delegate/contracts/interfaces/IDelegate.sol, source/delegate/test/Delegate.js, source/delegate/test/DelegateIntegration.js
* Rename DelegateSwap to DelegatedSwapFor to match Wrapper behavior.
* Add senderWallet parameter to DelegatedSwapFor.
* Index all three parameters of DelegatedSwapFor.
=> DelegatedSwapFor event for Delegate
